image: amardikian/clang-3.8

stages:
  - build
  - configure
  - test

configure:
  stage: configure
  script:
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake ..
  artifacts:
    untracked: true

build:
  stage: build
  script:
    - cd cmake-build-debug
    - make
  artifacts:
    paths:
      - cmake-build-debug/interface/libinterface.so
      - cmake-build-debug/backend/libbackend.so
      - cmake-build-debug/executable/executable


test:
  stage: test
  script:
    - cmake-build-debug/executable/executable


