# image: amardikian/clang-3.8

stages:
  - configure
  - build
  - test

configure:
  stage: configure
  script:
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake ..
  artifacts:
    untracked: true
  tags:
    - imac

build:
  stage: build
  script:
    - cd cmake-build-debug
    - make
  artifacts:
    paths:
      - cmake-build-debug/interface/libinterface.dylib
      - cmake-build-debug/backend/libbackend.dylib
      - cmake-build-debug/executable/executable
  tags:
    - imac

test:
  stage: test
  script:
    - tree cmake-build-debug
    - cmake-build-debug/executable/executable
  tags:
    - imac


