

stages:
  - build
  - configure
  - test

configure:
  stage: configure
  script:
    - apt-get install cmake
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake ..
  artifacts:
    paths:
      - cmake-build-debug




