image: amardikian/clang-3.8

stages:
  - build
  - configure
  - test

configure:mac:gcc:
  stage: configure
  script:
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake ..
  artifacts:
    untracked: true




